Add board list view,test and templates
SourabhTestpress/NewBoardApp pull request #7
Opened 2020-09-24 10:50 UTC by SourabhTestpress

**Things Imporoved:**

- Absolute import used instead of '..views'

- Tried to name tests according to "test_action_produces_result"

- self.assertEquals(expected_value, obtained_value) done previously it was (obtained_value, expected_value)

- Proper formatting used for scripts tags

- directly hrefs used instead of using Javascript.

**Things that could not be improved:**

- Tried directly calling view as well as by resolve() method but not working. So, sticked to Testcase Client()

**Stats**

    Number of Test Cases - 5
    Number of SQL Queries - 1

**Guidelines**

PEP8(Python)/Testpress JS compatible Yes
Is each logical block separated with a line break? Yes
Have you self reviewed this PR in context to the previous PR feedbacks? Yes

2020-09-24 10:51 UTC, SourabhTestpress commented on boards/tests/test_views.py
> +        response = self.client.get(url)
Tried calling view but It was not working so, I had to use client.

2020-09-24 11:25 UTC, SourabhTestpress commented on boards/tests/test_views.py
> +        response = self.client.get(url)
Now I relaize, I can use RequestFactory to avoid middleware and exception . I am going to change this line by RequestFactory.

2020-09-24 11:59 UTC, waranlogesh requested changes

2020-09-24 11:59 UTC, waranlogesh commented on boards/tests/test_template.py
> +        Board.objects.create(name="1st", slug="first", description="duplicated")
Use bulk create.

2020-09-24 11:59 UTC, waranlogesh commented on boards/tests/test_template.py
> +        url = reverse("home")
Use it directly.

2020-09-24 11:59 UTC, waranlogesh commented on boards/tests/test_template.py
> +        url = reverse("home")
.

2020-09-24 11:59 UTC, waranlogesh commented on boards/tests/test_views.py
> +class BoardListViewTests(TestCase):
Use SimpleTestCase since it doesn't involve any DB operations.

2020-09-24 11:59 UTC, waranlogesh commented on boards/urls.py
> +    path("board/<str:slug>/", views.board_details, name="board_details"),
<img width="717" alt="Screenshot 2020-09-24 at 5 21 36 PM" src="https://user-images.githubusercontent.com/9105503/94141498-729c2880-fe8a-11ea-9dfc-ed5c44641448.png">

2020-09-24 11:59 UTC, waranlogesh commented on templates/boards/board_list.html
> +{% extends 'base.html' %}
board prefix not needed.

2020-09-24 11:59 UTC, waranlogesh commented on templates/boards/board_list.html
> +<style type="text/css">
Follow proper indentations in all html and css codes.

2020-09-24 11:59 UTC, waranlogesh commented on boards/views.py
> +def board_details(request, slug):
board_detail

2020-09-24 11:59 UTC, waranlogesh commented on boards/views.py
> +#  Imports from this folder
![Uploading Screenshot 2020-09-24 at 5.26.49 PM.png…]()

2020-09-24 11:59 UTC, waranlogesh commented on boards/tests/test_template.py
> +# imports from this folder
<img width="751" alt="Screenshot 2020-09-24 at 5 28 39 PM" src="https://user-images.githubusercontent.com/9105503/94142117-65336e00-fe8b-11ea-94ce-a37c9afff74a.png">

2020-09-25 08:34 UTC, waranlogesh approved these changes

2020-09-25 08:35 UTC, merged